AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'myECM Global Setup'


## Bucket names - override in sam deploy for custom names
Parameters:
  TPBucketName:
    Type: String
    Default: 'myecm-s3-tp'
  BATCHBucketName:
    Type: String
    Default: 'myecm-s3-batch'
  ECSBucketName:
    Type: String
    Default: 'myecm-s3-ecs'

## S3 buckets
Resources:
  TPBucket:
    Type: AWS::S3::Bucket  
    Properties:
      BucketName: !Ref TPBucketName
  BATCHBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BATCHBucketName
  ECSBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref ECSBucketName

# Used by any target functions to access the S3
# buckets. If more buckets need to be added, add here
# instead of at each function.

  MyManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: indexation-buckets-read-policy
      PolicyDocument: 
        Version: 2012-10-17
        Statement: 
          - Effect: Allow
            Action:
              - s3:GetObject
              - s3:ListBucket
              - s3:GetBucketLocation
              - s3:GetObjectVersion
              - s3:GetLifecycleConfiguration
              - s3:PutObject
              - s3:DeleteObject
            Resource:
              - !Sub 'arn:aws:s3:::${TPBucket}/*'
              - !Sub 'arn:aws:s3:::${BATCHBucket}/*'
              - !Sub 'arn:aws:s3:::${ECSBucket}/*'

## Outputs
Outputs: 
  TPBucketName:
    Description: TP Indexation Bucket
    Value: !Ref TPBucket
  BATCHBucketName:
    Description: BATCH Indexation Bucket
    Value: !Ref BATCHBucket
  ECSBucketName:
    Description: ECS Storage Bucket
    Value: !Ref ECSBucket