#!/bin/bash

echo
echo "Provision myECM stack"
echo

echo "Build Artifacts"
sam build

echo
echo "Deploy Stack"
sam deploy --capabilities CAPABILITY_NAMED_IAM --stack-name myecm --resolve-s3 --debug

echo
echo "Sync S3 WebSite"
aws s3 sync ACQsite/. s3://myecm-s3-acq
