AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'myECM Files Loader'

#Parameters:
#  ESdomain:
#    Type: String
#    Default: 'YOUR-ES-ENDPOINT.us-east-1.es.amazonaws.com'

Resources:
  # EventBridge rules 
  EventRuleDBLoader: 
    Type: AWS::Events::Rule
    Properties: 
      Description: "myECM load to DB"
      State: "ENABLED"
      EventPattern: 
        source: 
          - "myecm.analyzers"
      Targets: 
        - Arn: 
            Fn::GetAtt: 
              - "LoadToDBFunction"
              - "Arn"
          Id: "LoadToDB"            

  # EventBridge permissions to invoke Lambda functions
  PermissionForEventsToInvokeLambda1: 
    Type: AWS::Lambda::Permission
    Properties: 
      FunctionName: 
        Ref: "LoadToDBFunction"
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn: 
        Fn::GetAtt: 
          - "EventRuleDBLoader"
          - "Arn"

  # Lambda functions
  LoadToDBFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: loadToDB/
      Handler: app.handler
      Runtime: nodejs12.x
      Timeout: 5
      MemorySize: 128
      Policies:
      # Read more about SAM policy templates here
      # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-templates.html
       - AWSLambdaExecute
       - DynamoDBCrudPolicy:
          TableName: !Ref MyECMDynamoDBTable
      Environment:
        Variables:
          DBTableName: !Ref MyECMDynamoDBTable
  
  MyECMDynamoDBTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      #TableName: MyECMTable
      AttributeDefinitions:
        - AttributeName: Id
          AttributeType: S
        - AttributeName: Type
          AttributeType: S
        - AttributeName: Date
          AttributeType: S
      KeySchema:
        - AttributeName: Id
          KeyType: HASH
        - AttributeName: Date
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      ProvisionedThroughput:
        ReadCapacityUnits: 0
        WriteCapacityUnits: 0
      GlobalSecondaryIndexes:
        - IndexName: type-index
          KeySchema:
            - AttributeName: Type
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 0
            WriteCapacityUnits: 0
       
